README.md
fluent-plugin-kafka.gemspec
lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka_buffered.rb

To support Kafka compression in out_kafka and out_kafka_bufferd, add a new configuration parameter `compression_codec` and pass the value to Poseidon's producers.

Add compression support in output plugins

---

README.md
lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka_buffered.rb

The out_kafka and out_kafka_buffered plugins have their own implementations for multiple output formats (w/ `output_data_type` option), but not have supports for Fluentd formatter plugins.
To support formatter plugins, make output plugins create formatter plugin instance and call its `format` method when unknown value is passed at `output_data_type`. 
For example, when the following configuration is passed, the output plugin uses `CsvFormatter` plugin to format the output data.
```
output_data_type csv
fields message
force_quotes false
```
This change has a potential to break backward compatibilities if the user already passes the unknown value to `output_data_type`.

Add formatter plugin support by calling formatter as a fallback for unknown output_data_type

---

lib/fluent/plugin/in_kafka.rb

Wrong port number 2181 was set for default port number for kafka broker.

Fix default port number for kafka broker

---

README.md
lib/fluent/plugin/in_kafka.rb

Should create a hash when input record is in plain text, otherwise the record
will be discarded by output plugins.  This was found in our use case: extract
plain text messages from kafka and output to elasticsearch.
See also: [fluentd/fluentd/issues/664](https://github.com/fluent/fluentd/issues/664#issuecomment-135394548).

Create a hash for input text message

---

lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka_buffered.rb

I find the issue #38 .
It seems that new producer is created without closing old producer connection.
This PR is closing producer connection when refresh producer.

Close producer connection when refresh producer

---

lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka_buffered.rb

- I want to add the `time_format` option. Because it does not use only unixtime.
```
time_format %Y-%m-%dT%H:%M:%S%z
```

Add time_format option

---

fluent-plugin-kafka.gemspec
lib/fluent/plugin/in_kafka.rb
lib/fluent/plugin/in_kafka_group.rb

Hi, I've tried to adopt Fluentd v0.14.
I've found that there are several problems and I fixed them.
* missing development dependency of test-unit gem
* missing `fluent/input` require
* sometimes missing calling `super` in `#start` and `#shutdown`

Adopt v0.14

---

fluent-plugin-kafka.gemspec
lib/fluent/plugin/out_kafka_buffered.rb

Use ruby-kafka for kafka v0.9 or v0.10 support.
In this PR, I plan to update only kafka_buffered.
We need stable consumer API for replacing input plugins.

Use ruby-kafka

---

README.md

The input plugin currently doesn't support `zookeeper_path`.  This was a source of confusion when trying out the plugin.

Removed the `zookeeper_path` option from the input config.

---

fluent-plugin-kafka.gemspec

ruby-kafka 0.3.9 improves producer performance so updating lower version is better.

Update ruby-kafka dependency to v0.3.9

---

lib/fluent/plugin/kafka_producer_ext.rb
lib/fluent/plugin/out_kafka_buffered.rb

This approach has two merits
- Improve CPU / memory usage by avoiding unnecessary object allocation
- Skip buffer size check
Output plugin has own buffer check mechanizm so we don't need buffer size check in ruby-kafka side.
Skipping it resolves https://github.com/htgc/fluent-plugin-kafka/issues/61 together.
Producer API is now stable so extend Producer seems acceptable for me.

Extend Kafka::Producer to improve out_kafka_buffered

---

lib/fluent/plugin/out_kafka.rb

Next step for removing poseidon dependency.

Use ruby-kafka instead of poseidon in out_kafka

---

fluent-plugin-kafka.gemspec
lib/fluent/plugin/in_kafka.rb
lib/fluent/plugin/in_kafka_group.rb
lib/fluent/plugin/kafka_plugin_util.rb

For supporting recent kafka versions.
Remove several parameters because ruby-kafka consumer approach is different from poseidon.
Note that consumer APIs in ruby-kafka is still alpha so we may hit the problems.
We need tests on several workload.
TODO: Remove zookeeper dependency from gem.

Replace poseidon with ruby-kafka in input pugins

---

README.md
lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka_buffered.rb

`required_acks 0` is fire-and-forget and
this is not good default value for almost users.
Default behaviour should be safe.
Refer: https://github.com/fluent/fluent-plugin-kafka/issues/69

Change default required_acks value to -1, wait all acks.

---

lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka_buffered.rb

The same way that is done for specifying the `partition_key` to use by embedding it in the message and then removing it, this pull request allows a client to do so with `partition` as well. Since the `ruby-kafka` client supports specifying the partition as an alternative to `partition_key`, this is a simple change and remains consistent with the `ruby-kafka` library.

Allow specifying the partition to use

---

lib/fluent/plugin/kafka_producer_ext.rb
lib/fluent/plugin/out_kafka2.rb

This is experimental for out_kafka replacement.
I want to replace `out_kafka` with `out_kafka2` since v1.0.

Add out_kafka2 for v0.14

---

README.md
lib/fluent/plugin/in_kafka_group.rb

* Related issue is #108.
* ruby-kafka's subscribe function supports max_bytes_per_partition parameter.
* refer to [link](https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/consumer.rb#L83)
* default value is 1048576(1M).

Add max_bytes option to in_kafka_group

---

README.md
lib/fluent/plugin/out_kafka_buffered.rb

This pull request is related to https://github.com/fluent/fluent-plugin-kafka/issues/117
And it's similar to https://github.com/fluent/fluent-plugin-kafka/issues/80
fluentd configuration file
```
<source>
@type forward
</source>
<match test.**>
type kafka_buffered
brokers host1:6667,host2:6667,host3:6667
buffer_chunk_limit 32M
flush_at_shutdown true
kafka_agg_max_bytes 40960
output_include_tag true
output_include_time true
time_format %Y-%m-%dT%H:%M:%S%z
output_data_type json
flush_interval 1
num_threads 10
required_acks 1
max_send_limit_bytes 100
</match>
```
fluentd-cat command
```
$ echo '{"hoge":"fugaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}' | fluent-cat test.fuga
```
warn log
```
2017-03-27 16:26:49 +0900 [warn]: record size exceeds …
```

Add max_send_limit_bytes option to avoid MessageSizeTooLarge

---

lib/fluent/plugin/out_kafka.rb

Solves https://github.com/fluent/fluent-plugin-kafka/issues/120.
When the buffer overflows, it delivers the messages and continues.

handling BufferOverflow exception in out_kafka

---

README.md
lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka_buffered.rb

Makes easy to mitigate https://github.com/fluent/fluent-plugin-kafka/issues/120.
Makes the parameters max_buffer_size and max_buffer_bytesize of ruby-kafka configurable.

make parameters of ruby-kafka configurable

---

README.md
lib/fluent/plugin/out_kafka_buffered.rb

Hi, I use Kafka 0.9 and fluent-plugin-kafka 0.5.4.
If user uses a period ('.') and underscore ('_') as kafka topic name, it's troublesome.
For example, user creates a.a_a topic
```
$ bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic a.a_a
WARNING: Due to limitations in metric names, topics with a period ('.') or underscore ('_') could collide. To avoid issues it is best to use either, but not both.
Created topic "a.a_a".
```
but, user sends message to a.a.a topic.
```
<source>
@type forward
</source>
<match a.a.a>
type kafka_buffered
brokers localhost:9092
flush_interval 1
</match>
```
```
$ echo '{"hoge":"fuga"}' | fluent-cat a.a.a
```
Error occurs as follows
```
2017-04-18 10:52:43 +0900 [warn]: temporarily failed to flush the buffer. …
```

Add discard_kafka_delivery_failed option to handle Kafka::DeliveryFailed

---

README.md
lib/fluent/plugin/out_kafka_buffered.rb

Hi.
I'd like to add an option for batch transfer, which sets an upper limit on the number of messages.
Currently, `kafka_agg_max_bytes` can set an upper limit on the number of bytes, but we also want to limit the number of messages.
If only `kafka_agg_max_bytes` is used, there is a possibility that a lot of small logs are packed in one batch.
The number of logs in one batch affects the number of duplicate logs at retransmission, so I would like to control this with the parameter `kafka_agg_max_messages`.
Also, `kafka_agg_max_bytes` is an important parameter affecting throughput, but there is no explanation in the `README.md`. I think that adding the explanation to the `README.md` is more helpful to the user.

Add kafka_agg_max_messages option

---

README.md
lib/fluent/plugin/out_kafka_buffered.rb

#139 
ruby-kafka supports Statsd and Datadog monitoring.
https://github.com/zendesk/ruby-kafka#monitoring
ruby-kafka 4.0 supports statsd.
https://github.com/zendesk/ruby-kafka/pull/373
This pull request enables to monitor kafka client by using datadog or statsd
sample fluentd conf
```
<source>
@type forward
</source>
<match aaa>
type kafka_buffered
statsd_monitoring true
get_kafka_client_log true
brokers localhost:9092
flush_interval 1
</match>
```
sample Gemfile
```
source 'https://rubygems.org'
gem "fluent-plugin-kafka",:git=>"https://github.com/wyukawa/fluent-plugin-kafka.git", :ref => "281f1b66cd303ea8b16333364dba21771bbad922"
gem "statsd-ruby"
gem "activesupport", "5.1.2"
gem "fluentd", "0.12.33"
```
I confirmed by using https://github.com/prometheus/statsd_exporter
I can't confirm …

Add statsd and datadog monitoring

---

lib/fluent/plugin/in_kafka.rb
lib/fluent/plugin/in_kafka_group.rb

When I used this plugin for consuming ltsv format topics from kafka brokers.
```td-agent.conf
<source>
@type kafka_group
brokers              kafka01:9092,kafka02:9092,kafka03:9092,
consumer_group       test_consumer01
topics               target_topics01
format               ltsv
add_prefix           kafka
use_record_time      true
time_format          %Y-%m-%dT%H:%M:%S%:z
start_from_beginning false
</source>
```
Encountered below error.
It seems LTSV parsed result record's keys are symbol, not string.
So, set symbolize_keys => false, for ltsv parse option.
> 2017-11-01 09:30:11 +0900 [warn]: parser error in target_topics01/1 error="value must be string: " value="method:GET\turi:/ranking?pageSize=10\tprotocol:HTTP/1.1\tstatus:200\tsize:22573\treqtime:0.116\tlanguage:-\tsession:-\tscheme:h …

Parsed ltsv format, records' keys should be string, not symbol.

---

fluent-plugin-kafka.gemspec

I hope ruby-kafka doesn't break API without announcement.

Relax ruby-kafka version. fix #163

---

lib/fluent/plugin/out_kafka2.rb

When I used this plugin in version v3.1.1(Fluentd v1.0.2), warning log printed in process starting process.
```td-agent.conf
<match **>
@id                         output_log_to_kafka
@type                       kafka2
@log_level                  warn
brokers                     kafka01:9092,kafka02:9092,kafka03:9092,
topic_key                   topic
exclude_topic_key           true
<buffer topic,tag>
@type                       file
path                        "/var/log/td-agent/buffer/output_log_to_kafka.*.log"
flush_interval              2s
flush_thread_interval       2s
flush_thread_burst_interval 1s
retry_forever               true
retry_max_interval          300s
chunk_limit_size            16m
queue_limit_length          100
</buffer>
</match>
```
```
2018-02-28 16:58:10 +0900 …
```

Fix warning log condition.

---

README.md

Fix typo kafka2 setting example.

---

lib/fluent/plugin/in_kafka.rb
lib/fluent/plugin/in_kafka_group.rb

When I used this plugin in version v3.1.1(Fluentd v1.0.2), below error occured in process starting process.
```td-agent.conf
<source>
@type kafka_group
brokers              kafka01:9092,kafka02:9092,kafka03:9092,
consumer_group       test_consumer01
topics               target_topics01
format               ltsv
add_prefix           kafka
use_record_time      true
time_format          %Y-%m-%dT%H:%M:%S%:z
start_from_beginning false
</source>
```
```
2018-02-28 17:26:49 +0900 [error]: unexpected error error_class=NameError error="uninitialized constant Fluent::TextParser\nDid you mean?  Fluent::TimeParser"
2018-02-28 17:26:49 +0900 [error]: /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.6.6/lib/fluent/plugin/in_kafka_group.rb:111:in `configure'
2018-02-28 17:26:49 …
```

Fix TimeParser class name for fluentd_0.14.7 or later.

---

lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka_buffered.rb

in ruby a split even without split char present will return require list
```
>> "a:4321,b:4321,c:4321".split(",")
=> ["a:4321", "b:4321", "c:4321"]
>> "a:4321".split(",")
=> ["a:4321"]
```
Signed-off-by: AbhishekKr <abhikumar163@gmail.com>

removing ternary for seed_brokers, result is as reqd. on no match split

---

lib/fluent/plugin/out_kafka2.rb

By https://github.com/fluent/fluent-plugin-kafka/pull/168, kafka client's seed_brokers parameter switched to @seed_brokers.
To format with other plugin's parameter name, add initialization @seed_brokers from brokers.

Add initialize @seed_brokers in out_kafka2 plugin.

---

lib/fluent/plugin/out_kafka2.rb
lib/fluent/plugin/out_kafka_buffered.rb

v0.7.0 removes `logger` param from Kafka initialization unexpectedly.

Fix regression of get_kafka_client_logs. fix #186

---

lib/fluent/plugin/kafka_plugin_util.rb
lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka_buffered.rb

Hi,
When certificate is specified in configuration, I would like to extract endpoint which is SSL from endpoints obtained from Zookeeper.
The version of kafka used for check is 1.0.0.
For example, when I set `PLAINTEXT: //192.0.2.11: 9092, SSL: //192.0.2.11: 9093` to `ADVERTISED_LISTENERS`. Broker information which can be retrieved from `zookeeper:///brokers/ids/1001` is as follows.
```
{
"listener_security_protocol_map": {
"PLAINTEXT": "PLAINTEXT",
"SSL": "SSL"
},
"endpoints": [
"PLAINTEXT://192.0.2.11:9092",
"SSL://192.0.2.11:9093"
],
"jmx_port": -1,
"host": "192.0.2.11",
"timestamp": "1526455616183",
"port": 9092,
"version": 4
}
```

pickup ssl_endpoint from zookeeper node

---

lib/fluent/plugin/out_kafka2.rb

https://github.com/fluent/fluent-plugin-kafka/blob/master/lib/fluent/plugin/out_kafka2.rb#L132-L140
To use `router.emit()` with the v1 API output plugin, it must include `event_emitter` helper.

out_kafka2: fix to include event_emitter helper

---

lib/fluent/plugin/out_kafka2.rb

Setting message key by message_key_key in config file does not work due to mismatch between the definition and the reference in out_kafka2.

Fix mismatch between config param and reference of message_key_key.

---

lib/fluent/plugin/out_kafka2.rb

hello, 
for using in output kafka2, I made it to skip ruby-kafka exception. (like skip Kafka::MessageSizeTooLarge)
and add some parameter to backup what chunks make exception occur.
I'm not used to ruby, so give me some feedbacks ^^;
thanks

add parameter for exception ignore in kafka2

---

lib/fluent/plugin/in_kafka_group.rb

Hi. 
I think retry optioin is necessary option.
I have tested it in kubernetes environment.
please check my patch . 
issue: https://github.com/fluent/fluent-plugin-kafka/issues/192

Add retry_limit,disable_retry_limit to reconnect to kafka

---

README.md
lib/fluent/plugin/in_kafka_group.rb

-  Be tunable fetcher_max_queue_size because of tuning fluentd's max process memory size.
- Now, ruby-kafka's Fetcher holds fetched batch messages in memory.
- https://github.com/zendesk/ruby-kafka/blob/v0.6.8/lib/kafka/fetcher.rb#L13
- (default 100) https://github.com/zendesk/ruby-kafka/blob/v0.6.8/lib/kafka/client.rb#L291
- But, Fetcher's message means "Batched message fetched from all partisions what be assined to consumer.".
- So, Fetcher's message size is estimated blow.
- (One fetch result from partition , Max max_bytes=1MB) * (Num of Assined Partition) * fetcher_max_queue_size(100) * Compression Rate
- Max 500MB over per partition.
- Therefore, in environment what has many partitions, fluentd process's memory size has become very large.
- 5GB or over.
- So, if …

Be tunable fetcher_max_queue_size for kafka_group

---

fluent-plugin-kafka.gemspec
lib/fluent/plugin/kafka_producer_ext.rb
lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka2.rb
lib/fluent/plugin/out_kafka_buffered.rb

Adding support to not use SSL when using SASL
According to the documentation it is possible to not force the use of SSL when using SASL authentication.
Since in some cases the Kafka cluster is inside the same network without external access, using SSL is a bit of overkill.
Added the possibility to not use SSL for the Fluentd plugin by passing the **sasl_over_ssl false**
Updated required version of ruby-kafka to 0.7.1 due to the support of not using SSL with SASL in that version
Also had to update the Producer.produce2 method (and renamed to Producer.produce_for_buffered) to comply with the new call to PendingMessage.new()

Support to not force SSL with SASL

---

lib/fluent/plugin/out_kafka2.rb
lib/fluent/plugin/out_kafka_buffered.rb

`transactional_id` support is TODO.

output: Add idempotent parameter for idempotent producer. ref #219

---

lib/fluent/plugin/in_kafka_group.rb

Greetings,
While working with Fluentbit Kafka output and this plugin input, I noticed that I could not use the `use_record_time` option as the time was written as a unix timestamp with added milliseconds because it was sent as a number.
This change simply cast the `record['time']` field before attempting to parse it, allowing us to have something like:
```
<source>
@type kafka_group
brokers XXX
consumer_group XXX
topics XXX
format msgpack
use_record_time true
time_format "%s.%L" 
</source>
```
Let me know if this change is useful and if it was the correct way to do this, or it was an issue on my end.

fix: convert record's time to string before attempting to parse it

---

README.md
lib/fluent/plugin/out_kafka2.rb

This option is useful when kafka cluster doesn't allow automatic topic creation.

out_kafka2: Add use_default_for_unknown_topic parameter

---

lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka2.rb
lib/fluent/plugin/out_kafka_buffered.rb

Following the same applications of sasl ha256, passing variable
sasl_over_ssl to the constructor when using plain auth.

Allow setting to not use ssl with plain password

---

README.md
lib/fluent/plugin/out_kafka_buffered.rb

Enable the setting of partition_key which has been invalid due to typo.
Additionally, I found some mistakes at the section [load-balancing](https://github.com/KeiichiHirobe/fluent-plugin-kafka#load-balancing),  and I fix that.

Enable the setting of partition key

---

lib/fluent/plugin/in_kafka_group.rb

We were running on a problem where we ultimately solved by exposing 2 parameters from ruby-kafka connections to kafka-group ingestion: connect_timeout and socket_timeout
From here: https://github.com/zendesk/ruby-kafka/blob/master/lib/kafka/connection.rb#L49
Our remote brokers over SSL needed the socket_timeout increased from the default in order to wait for "join_group", otherwise we ended up in a non-stop rebalancing cycle at the brokers.

Expose connection timeouts

---

lib/fluent/plugin/out_rdkafka2.rb

Without this patch, No method error could be raised here.
@repeatedly Could you review this?

`chunk.metadata.variables` could be nil

---

lib/fluent/plugin/out_kafka2.rb

`chunk.metadata.varialbes` can be and defaults to `nil`.
Need to handle that case.
This was already fixed for rdkafka2.
Signed-off-by: Kevin S Kirkup <kevin.kirkup@pureport.com>

Fix chunk.metadata.variables can be nil for kafka2

---

fluent-plugin-kafka.gemspec
lib/fluent/plugin/kafka_plugin_util.rb
lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka2.rb
lib/fluent/plugin/out_kafka_buffered.rb

Hi. I would like to configure `ssl_verify_hostname` of ruby-kafka which is added in https://github.com/zendesk/ruby-kafka/pull/733

Add configuration for ssl_verify_hostname

---

README.md
lib/fluent/plugin/kafka_producer_ext.rb
lib/fluent/plugin/out_kafka2.rb
lib/fluent/plugin/out_rdkafka2.rb

I'd like to be able to define headers on a Kafka message based on the content of a fluentd record.
This is due to the Splunk Kafka Connect plugin using Kafka headers to populate some metadata about an event in Splunk ([source](https://github.com/splunk/kafka-connect-splunk#headers-parameters)).
---
I've raised this PR to see if the maintainer is interested in the contribution. No offence taken if not, I'd be wary about accepting new code without any automated tests.

Enable defining headers for kafka2 and rdkafka2 output

---

lib/fluent/plugin/kafka_producer_ext.rb
lib/fluent/plugin/out_kafka2.rb
lib/fluent/plugin/out_kafka_buffered.rb

Replacement for https://github.com/fluent/fluent-plugin-kafka/pull/278

Add use_event_time to use fluentd event time for CreateTime. fix #273

---

lib/fluent/plugin/in_kafka.rb
lib/fluent/plugin/in_kafka_group.rb

Output plugins have this parameter. This avoids latest ruby-kafka's logger bug.

input: Add get_kafka_client_log parameter. ref #280

---

lib/fluent/plugin/in_kafka.rb
lib/fluent/plugin/in_kafka_group.rb

This change adds the sasl_over_ssl paramter to plain sasl consumer
constructor calls so that sasl_over_ssl can be disabled.
Signed-off-by: Steven Fitzpatrick <StevTheDev@gmail.com>

Add sasl_over_ssl parameter to plain sasl consumer constructor calls

---

README.md

Add description of time_source in input plugin. 
I needed kafka timestamp, but there was no description in README.md. But, for the kafka timestamp, the time_source record was already implemented in the code, and it was necessary to explain it.

Add description of time_source in README.md

---

lib/fluent/plugin/in_kafka_group.rb

The backing function "subscribe" in ruby-kafka supports topics specified
in string or regex objects. This commit exposes that feature.
in_kafka.rb uses a different function that only supports strings.

Expose topic regex matching support.

---

lib/fluent/plugin/in_kafka.rb
lib/fluent/plugin/in_kafka_group.rb

When we set time_source to record, we can specify time field instead of fixed value, 'time'.

Add custom time key when time_source is record

---

lib/fluent/plugin/kafka_producer_ext.rb

The newest version of ruby-kafka changed the Kafka::Partitioner API from `partition_for_key` to `call`: https://github.com/zendesk/ruby-kafka/commit/8dc495f471312834e477cd16144a32295c6b0a65#diff-0bc0466ba80bcb74058c1e4def09bf41R22

Fix partitioner call in Kafka::Producer due to ruby-kafka change

---

lib/fluent/plugin/in_kafka.rb

#351 fixed this for the `kafka_group` input plugin. This PR adds it for the `kafka` plugin.

Expose ssl_verify_hostname for Kafka input plugin

---

lib/fluent/plugin/in_kafka.rb

This PR is to fix #380 
It simply supplies `record_time_key` as additional argument in the `TopicWatcher` class constructor, which was missing until now, which led the option to use the `record` time_source to not work.

Fix: record_time_key not working in in_kafka.rb

---

lib/fluent/plugin/in_kafka_group.rb

The [fluentd documentation](https://docs.fluentd.org/configuration/format-section#time-parameters) says:
```
time_type (enum) (optional): parses/formats value according to this type
Default: float (econds from Epoch + nano seconds (e.g.1510544836.154709804))
```
But the `float` type is not supported by default in this library. As a result, an [error raises](https://github.com/fluent/fluentd/blob/v1.11.5/lib/fluent/plugin/output.rb#L828):
```
time must be a Fluent::EventTime (or Integer): Float
```
I suggest using parser [Fluent::NumericTimeParser](https://github.com/fluent/fluentd/blob/v1.11.5/lib/fluent/time.rb#L282) for float times like other [plugins do](https://github.com/fluent/fluentd/blob/v1.11.5/lib/fluent/time.rb#L182).
P.S. Use [time_format …

Use NumericTimeParser to parse float time

---

lib/fluent/plugin/in_kafka.rb
lib/fluent/plugin/in_kafka_group.rb

This PR adds the option to set the Fluentd event tag to a record field instead of the topic name only (similar to the existing `time_source` option).
We created this on our side as we have the need to keep the source event tags when we have a Fluentd on a source cluster and another one on a target cluster where a Kafka topic is acting as queue in between.

Add option to use record as source for the Fluentd event tag

---

lib/fluent/plugin/kafka_plugin_util.rb
test/plugin/test_kafka_plugin_util.rb

Signed-off-by: Jeff Cantrill <jcantril@redhat.com>
This resolves an issue where trying to dynamically configure SSL and path is empty string instead of nil where it errors like:
```
2020-09-29 14:44:52 +0000 [error]: unexpected error error_class=Errno::ENOENT error="No such file or directory @ rb_sysopen - "
2020-09-29 14:44:52 +0000 [error]: /usr/local/share/gems/gems/fluent-plugin-kafka-0.13.1/lib/fluent/plugin/kafka_plugin_util.rb:41:in `read'
2020-09-29 14:44:52 +0000 [error]: /usr/local/share/gems/gems/fluent-plugin-kafka-0.13.1/lib/fluent/plugin/kafka_plugin_util.rb:41:in `read_ssl_file'
```
from `ssl_client_cert_key "#{File.exist?('{{ $tlsKey }}') ? '{{ $tlsKey }}' : nil"`

Treat empty string in read_ssl_file as nil

---

lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka_buffered.rb

Ruby 3.0.0 keywords arguments do not permit Hash <-> keyword arguments
interop.
Instead, we should add a double asterisk operator(`**`) for it.
Otherwise, Fluentd which is working with Ruby 3.0.0 complains the following error:
```log
2021-03-17 11:30:35 +0900 [warn]: #0 Send exception occurred: wrong number of arguments (given 1, expected 0)
2021-03-17 11:30:35 +0900 [warn]: #0 Exception Backtrace : /Users/cosmo/GitHub/fluentd/vendor/bundle/ruby/3.0.0/gems/ruby-kafka-1.3.0/lib/kafka/client.rb:261:in `producer'
/Users/cosmo/GitHub/fluentd/vendor/bundle/ruby/3.0.0/gems/fluent-plugin-kafka-0.16.0/lib/fluent/plugin/out_kafka_buffered.rb:242:in `block in get_producer'
/Users/cosmo/GitHub/fluentd/vendor/bundle/ruby/3.0.0/gems/fluent-plugin-kafka-0.16.0/lib/fluent/plugin/out_kafka_buffered.rb:239 …
```

out_kafka: out_kafka_buffered: Support Ruby 3.0.0 keyword arguments interop

---

ChangeLog
fluent-plugin-kafka.gemspec

This version can be running with Ruby 3.
Our Ruby 3 use case should block Ruby 3 hash interop incompatibility.
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>

Release v1.16.1

---

lib/fluent/plugin/in_kafka.rb
lib/fluent/plugin/in_kafka_group.rb

`@producer_opts` and `@consumer_opts` are also needed to hand-written
keyword argumtes interop on Ruby 3.
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>

in_kafka: in_kafka_group: Support Ruby 3.0.0 keyword arguments interop

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yaml

It is also useful to bug report/feature request in forms even though it is still in beta.
ref. https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
See https://github.com/fluent/fluentd/issues/new/choose for actual use case.

Use issue forms for bug report and feature request

---

README.md
fluent-plugin-kafka.gemspec
lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka2.rb
lib/fluent/plugin/out_kafka_buffered.rb
test/helper.rb
test/plugin/test_kafka_plugin_util.rb
test/plugin/test_out_kafka.rb
test/plugin/test_out_kafka2.rb
test/plugin/test_out_kafka_buffered.rb

Fixes https://github.com/fluent/fluent-plugin-kafka/issues/397.
Kafka#new can handle Kafka::Partitioner classes which determine partitioner algorithms such as `crc32` and `murmur2`.
In Java based kafka client, default partitioner algorithm is murmur2 not crc32.
This default algorithm glitch causes different partion assignment between Java based Kafka client and Ruby based one.

Provide hash function choices

---

README.md
lib/fluent/plugin/out_kafka2.rb
lib/fluent/plugin/out_rdkafka2.rb
test/plugin/test_out_kafka2.rb

I would like to exclude fields from message record.
This is desirable when using another configs such as `headers_from_record`, wich duplicates data to message headers. With this config will be possible to move data to headers and remove from the message payload.

Enable excluding record fields

---

lib/fluent/plugin/in_kafka.rb
lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka_buffered.rb

Suppress the following warnings:
```
/home/runner/work/fluent-plugin-kafka/fluent-plugin-kafka/lib/fluent/plugin/out_kafka_buffered.rb:181: warning: instance variable @field_separator not initialized
/home/runner/work/fluent-plugin-kafka/fluent-plugin-kafka/lib/fluent/plugin/in_kafka.rb:244: warning: instance variable @zookeeper not initialized
/home/runner/work/fluent-plugin-kafka/fluent-plugin-kafka/lib/fluent/plugin/out_kafka.rb:153: warning: instance variable @field_separator not initialized
```

Suppress warnings while running tests

---

lib/fluent/plugin/out_rdkafka2.rb

The usage of `Rdkafka::Config.logger.add` is changed since 0.9.0:
https://github.com/appsignal/rdkafka-ruby/commit/3f9e5045e09420b5213859b02fae894bb001caf2#diff-98e932d49ef97cb9149e0d0e280d10f841f644f6f1b3b67313552fff22b16a33
It should be same behaviour with `Logger#add`
Fix #414

Adapt the logger to rdkafka 0.9.0 or later

---

lib/fluent/plugin/out_rdkafka.rb

For out_rdkafka2 we fixed it in #423, but we forgot to fix the same
issue in out_rdkafka.

out_rdkafka: Adapt the logger to rdkafka 0.9.0 or later

---

lib/fluent/plugin/out_kafka.rb
lib/fluent/plugin/out_kafka2.rb
lib/fluent/plugin/out_rdkafka.rb
lib/fluent/plugin/out_rdkafka2.rb

If `max_send_limit_bytes` is set, skipped large events are dumped as
warning log. It will fill up logs quickly and it might cause DoS.

Don't output skipped large events as warning log

---

lib/fluent/plugin/out_kafka_buffered.rb

out_kafka_buffered: Don't output skipped large events as warning log

---

README.md
lib/fluent/plugin/in_kafka_group.rb
test/plugin/test_in_kafka_group.rb

Add parameter `refresh_topic_interval` which sets how often ruby-kafka
will refresh the list of topics. This is especially important to us
because new topics are very likely to be created and we want to consume
messages from them automatically.
Fixes https://github.com/fluent/fluent-plugin-kafka/issues/383.
Relevant code from ruby-kafka:
https://github.com/zendesk/ruby-kafka/blob/v1.4.0/lib/kafka/client.rb#L364

in_kafka_group: add refresh_topic_interval parameter

---

lib/fluent/plugin/out_kafka2.rb
test/plugin/test_out_kafka2.rb

I'd like to use the option `resolve_seed_brokers` of `ruby-kafka` introduced in https://github.com/zendesk/ruby-kafka/pull/877 to support brokers' hostname with multiple addresses. This option is available since `ruby-kafka` 1.4.0.
ref. https://github.com/zendesk/ruby-kafka/releases/tag/v1.4.0
This PR adds an option `resolve_seed_brokers` and passes it to `Kafa#new`.

Add an option to support brokers' hostname with multiple addresses

---

README.md
lib/fluent/plugin/out_kafka2.rb

Hey :wave: 
This PR changes the output `kafka2` plugin to reuse Kafka connections between flushes. Majority of the logic is lifted-and-shifted from the output `rdkafka2` plugin. I'm not able to run the unit test locally to verify whether this is working unfortunately (More than happy to create a follow up PR so we can run our test locally though!). It would be awesome if we can trigger a CI run to verify things are not broken :bowing_man:.
Thanks a bunch!
Some data points on why this is important:
- We were using https://github.com/fluent-plugins-nursery/fluent-plugin-formatter-protobuf as our formatter, in combination with the `kafka2` output plugin, we're able to comfortably handle ~4,500 - 5,000 messages per second per container (2 vCPU, 2GB memory each)
- We have load tested fluentd …

perf(out_kafka2): Reusing Kafka connections between flushes

---

lib/fluent/plugin/kafka_producer_ext.rb
lib/fluent/plugin/out_kafka2.rb

Fixes https://github.com/fluent/fluent-plugin-kafka/issues/462
Additionally, I just realised there's also a slight behavior change made in https://github.com/fluent/fluent-plugin-kafka/pull/454.
Prior to that commit, we were fetching Kafka topic related metadata only for the given topics, but that commit changes it such that the plugin fetches metadata for all topics. I don't think this will cause too much of an impact in production, but worth calling it out anyway.

fix(out_rdkafka2): fixed a bug where it is not respecting the Buffer sections' `chunk_limit_records` and `chunk_limit_size` options

---

README.md
examples/README.md
examples/out_kafka2/dynamic_topic_based_on_tag.conf
examples/out_kafka2/protobuf-formatter.conf
examples/out_kafka2/record_key.conf

This PR adds a couple of example configuration (with plans to add more in the future). I have also made some minor changes to the README for the out_kafka2 section.

docs(out_kafka2): added examples and added `topic` parameter to README

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/workflows/stale-actions.yml

We might not check issues so often recent days, so it is inappropriate to close stale issues that aren't checked by any maintainers. This commit will add waiting-for-triage label to all new issues and won't close them by default. In addition, issues that are assigned or set milestone are also exempted.

GitHub issue: Set waiting-for-triage by default

---

.github/dependabot.yml
.github/workflows/linux.yml

As v2 is deprecated, we migrate to v3 action.
See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12
Additionally added dependabot to watch deprecated actions.

Migrate to use GitHub v3 action

---

.github/workflows/linux.yml
Gemfile
lib/fluent/plugin/out_rdkafka2.rb

Fixes https://github.com/fluent/fluent-plugin-kafka/issues/463
I think this is the simplest implementation that I could find to support rdkafka 0.12.0, but unfortunately because of how we're monkey patching the methods, it means we'd have to drop support for < 0.12.0 thus making this a breaking change.
Not sure if this is the right place to propose whether we should consider splitting out rdkafka into its own plugin (say `fluent-plugin-rdkafka`) so we're able to put the rdkafka gem as a dependency in the gemspec and give it a proper version range.
The "test" for this change is that I have created a separate PR that only bumps rdkafka gem to 0.12.0 and nothing else. https://github.com/fluent/fluent-plugin-kafka/pull/469, then check its unit test logs …

fix(out_rdkafka2): fix compatibility with rdkafka 0.12.0

---

README.md
lib/fluent/plugin/out_rdkafka2.rb

Addresses https://github.com/fluent/fluent-plugin-kafka/issues/489
This lifts the same parameter from the `out_kafka2` plugin and behaves similarly - it first attempts to write to a given topic, and if it fails because the topic does not exist, it will attempt to write to the `default_topic`

feat(out_rdkafka2): adds `use_default_for_unknown_topic` configuration

---

README.md
lib/fluent/plugin/out_rdkafka2.rb

When with Forwarder and Aggregator architecture, forwarders sometimes send invalid data which cause delivery failure at aggregators. `out_rdkafka2` plugin has`discard_kafka_delivery_failed` but it potentially discards not only unnecessary events but also required events, e.g. users expect Fluentd to keep events in buffer files during the outage of Kafka cluster (due to maintenance for instance) but all events are discarded when with `discard_kafka_delivery_failed`.
This enhancement request proposes having `discard_kafka_delivery_failed_regex` option on `out_rdkafka2` plugin to nullify invalid data by checking the error message with given regexp pattern.
Here is a sample use case:
In the following configuration, dummy events are generated with tag `test-topic0001` and Fluentd try to ship …

Enhancement : Add "discard_kafka_delivery_failed_regex" option

---

README.md
lib/fluent/plugin/out_rdkafka2.rb

This is because msg_size_too_large and topic_authorization_failed error codes should be treated as an unrecoverable error. In Fluentd, we need to mark as unrecoverable with raise Fluent::Unrecoverable. But current implementation does not handle them as unrecoverable errors.

out_rdkafka2: Handle some of the exceptions as unrecoverable errors

---

lib/fluent/plugin/out_rdkafka2.rb

With https://github.com/fluent/fluent-plugin-kafka/pull/468,
rdkafka 0.12.0 specific patch was introduced, but rdkafka's internal change
was reverted later in 0.13.x.
So this monkey patch should be effective only between 0.12.0 and 0.12.1 (only 2 versions were shipped in 0.12.x).
For 0.13.x or later, it seems harmful.

Apply PR#468 patch only for 0.12.x.

---

lib/fluent/plugin/out_rdkafka2.rb

Reverts fluent/fluent-plugin-kafka#513
#505 is better approach to fix this problem, so revert this PR.

Revert "Apply PR#468 patch only for 0.12.x."

---

.github/workflows/linux.yml
README.md
lib/fluent/plugin/out_rdkafka2.rb
lib/fluent/plugin/rdkafka_patch/0_11_0.rb
lib/fluent/plugin/rdkafka_patch/0_12_0.rb
lib/fluent/plugin/rdkafka_patch/0_14_0.rb
lib/fluent/plugin/rdkafka_patch/0_16_0.rb

All PR are failing now because of rdkafka gem update.
The current code works with rdkafka 0.12.0,
and in 0.14.0 (there is no 0.13.0), the `Rdkafka::Producer` implementation has changed,
no more `@client` and `Rdkafka::Producer::Client`, 
now there is a `@native_client` and `Rdkafka::NativeKafka`.
No update on this part of the code between 0.14.0 and 0.15.0.
There is a constraint in the out_rdkafka2, on the `Rdkafka::Producer#close`, to add a timeout,
which is not part of the standard gem.
I try to update this behavior since following the current way to patch.
Thanks.

out_rdkafka2: add patch for new version of rdkafka

---

README.md
lib/fluent/plugin/out_rdkafka2.rb

**Which issue(s) this PR fixes:**
None.
**What this PR does / why we need it:**
In order to enable Idempotency for kafka producers, rdkafka allowes us to enable this. ([here](https://github.com/confluentinc/librdkafka/blob/master/CONFIGURATION.md/#L137))
**Docs Changes:**
README.md : Added to usage template for better visibility. 
**Release Note:**
Same as the title.

out_rdkafka2: enable idempotency for kafka producers

---

lib/fluent/plugin/kafka_producer_ext.rb

Which issue(s) this PR fixes:
https://github.com/fluent/fluent-plugin-kafka/issues/502
What this PR does / why we need it:
On enabling the get_kafka_client_log true, this can be figured out the leader of partitions is being queried multiple times: [here](https://github.com/zendesk/ruby-kafka/blob/62a0cf9c44b0c05a4f98c4ec073ae5f04f4194e0/lib/kafka/produce_operation.rb#L77C15-L77C15)
this metadata if refreshed by broker pool ([here](https://github.com/zendesk/ruby-kafka/commit/ffc1a341e923041c12fd230fdf1ff2f8b8c2e8df)). Adding this in producer would resolve the issue. 
additionally, this is a part of an optimisation done on ruby-kafka. 
Test cases passing post the changes.
Docs Changes:
NA

out_kafka2: Broker pool to take care of fetching metadata

---

.github/workflows/add-to-project.yml

It helps to track new issues by aggregating ones from Project view.

github: track issue with GitHub Project

---

.github/workflows/linux.yml

ruby/setup-ruby action installs the appropriate bundler for each Ruby version.
If the combination is inappropriate, it may not work as expected.
Related to https://github.com/fluent/fluent-plugin-kafka/pull/526#issuecomment-2639114023

ci: use bundler installed by ruby/setup-ruby action
