fluent/fluent-plugin-kafka

- lib/fluent/plugin/out_kafka_buffered.rb
I experienced a problem when using the out_kafka_buffered plugin in my fluentd environment.  
It was caused by many messages (I use the forest plugin so effectively only a single chunk is destined for a single topic) being sent in a send_messages call.  It was on the order of 15k messages which added up to about 8MB of serialized data per invocation.
When this happened all sorts of bad things started happening in fluent, particularly my forward input source wouldn't/couldn't keep up, and as a whole the entire fluentd process bogged down and eventually wouldn't be able to shutdown cleanly.  I usually gave up for the send_messages call to return after about 5 minutes.
During the process of fixing this problem, I disabled all aggregation of records and invoked send_messages per record, and …
> Problem when sending huge message blocks to poseidon 

- README.md
- lib/fluent/plugin/in_kafka.rb
Hi @htgc ,
I want to assign offset to each topic in in-plugin.
Because, I want to start processing from the assigned offset for specific topics.
I implemented it to set as follows.
```XML
<source>
type                    kafka
host                    127.0.0.1
port                    9092
format                  text
<topic>
topic           topic1
partition       0
offset          -1
</topic>
<topic>
topic           topic2
partition       0
offset          5
</topic>
</source>
```
Please check this request.
> Assign offset to each topic.

- lib/fluent/plugin/in_kafka.rb
Hi @htgc ,
I want to add offset info in record.
Because, I want to perform re-try with appointed offset when I fail in the middle of streaming processing.
To do so, I need to know the offset of message which processed the record.
Please check this request.
> Add offset info in record.

- lib/fluent/plugin/in_kafka.rb
Hi @htgc ,
I want to retry to pull message, when failed to emit record in in-plugin.
So, I implemented the option as follows.
1. When succeeded to emit process, the offset is saved in zookeeper.
1. When failed to emit process, the offset is not saved in zookeeper.
1. And retry to pull the message of finally saved offset.
I implemented it to set as follows.
```XML
<source>
type                  kafka
host                  127.0.0.1
port                  9092
topics                topic1,topic2  
format                text
offset_zookeeper      127.0.0.1:2181 ... zookeeper host and port.
offset_zk_root_node   /fluent/kafka ... zookeeper root node for saving offsets.
</source>
```
When set 'offset_zookeeper', enable this function.
Please check this reqeust.
> Managment offset in ZooKeeper

- README.md
- fluent-plugin-kafka.gemspec
- lib/fluent/plugin/in_kafka_group.rb
This is a follow up to fix issue #24.
> Consumer group

- lib/fluent/plugin/in_kafka.rb
- lib/fluent/plugin/in_kafka_group.rb
> Improve input plugins

- lib/fluent/plugin/out_kafka_buffered.rb
> Improve performance and memory usage of kafka_buffered

- lib/fluent/plugin/in_kafka.rb
- lib/fluent/plugin/in_kafka_group.rb
- lib/fluent/plugin/out_kafka.rb
- lib/fluent/plugin/out_kafka_buffered.rb
I cannot found some config  parameters descriptions in README and I does not add descriptions for them.
> Add config descriptions

- README.md
- lib/fluent/plugin/out_kafka.rb
- lib/fluent/plugin/out_kafka_buffered.rb
We have a custom structure in our zookeeper config that requires path prepending. This will add support for any custom path required, defaulting to the existing path
> Support for custom zookeeper broker path

- lib/fluent/plugin/out_kafka_buffered.rb
Small 2 changes
- Direct format call when use fomatter plugins
- Reduce buffering cost by removing tag
> Improve buffered output

- .gitignore
- .travis.yml
- README.md
- test/plugin/test_out_kafka.rb
I'm quietly improving this plugin and here's a set of cleanup-related tasks that don't change the functionality of the plugin, but improve the meta-repo information.  I've got a bug that I want to isolate with the tests that I'm starting to include, but I've yet to isolate that, so in the interim, hopefully these updates help.
> Travis CI integration, Updated README.md, Added .gitignore, and additional tests added

- README.md
- lib/fluent/plugin/out_kafka.rb
- lib/fluent/plugin/out_kafka_buffered.rb
Adding Options to remove topic and partition key
fixes #88
> Adding output_exclude_partition_key and output_exclude_topic_key option

- README.md
- lib/fluent/plugin/out_kafka.rb
- lib/fluent/plugin/out_kafka_buffered.rb
> To publish message key from Output plugin

- lib/fluent/plugin/in_kafka.rb
- lib/fluent/plugin/in_kafka_group.rb
Support for optional replacing of record's timestamp by value of 'time' field.
> Support for optional replacing of record's timestamp

- lib/fluent/plugin/in_kafka_group.rb
See https://github.com/fluent/fluent-plugin-kafka/issues/107
> Fix uninitialized constant in v0.14

- lib/fluent/plugin/out_kafka.rb
- lib/fluent/plugin/out_kafka2.rb
- lib/fluent/plugin/out_kafka_buffered.rb
This pull request allows a user of the plugin to specify a regular expression to subscribe to `ActiveSupport::Notifications` and then re-emit those notifications for processing downstream, such as with with `<match>` directives in the Fluentd configuration. This is useful because the Ruby Kafka gem [already supports ActiveSupport notifications](https://github.com/zendesk/ruby-kafka#instrumentation) allowing users to gather statistics and information.
> Add optional emit for active support notifications

- README.md
- lib/fluent/plugin/in_kafka.rb
- lib/fluent/plugin/in_kafka_group.rb
- lib/fluent/plugin/kafka_plugin_util.rb
- lib/fluent/plugin/out_kafka.rb
- lib/fluent/plugin/out_kafka2.rb
- lib/fluent/plugin/out_kafka_buffered.rb
> Preliminary support for sasl/gssapi authentication in ruby-kafka. 

- lib/fluent/plugin/in_kafka_group.rb
Hi @repeatedly 
Added a client_id in kafka_group plugin. Please take a look and merge.
Thanks,
Sharad Gaur
> Adding client_id in kafka_group plugin

- lib/fluent/plugin/kafka_plugin_util.rb
- lib/fluent/plugin/out_kafka.rb
- lib/fluent/plugin/out_kafka2.rb
- lib/fluent/plugin/out_kafka_buffered.rb
Simple patch to support PLAIN/SCRAM authentication
> Added support for PLAIN/SCRAM SASL

- README.md
I am very sorry...
(I'm sorry to have caused you trouble.)
Could you check with this?
Add CentOS Installation to README.md.
Signed-off-by: wlbhiro <wlbhiro@gmail.com>
> Add 'CentOS Installation'

- lib/fluent/plugin/kafka_plugin_util.rb
It stops the leak of Kafka password in logs
> Make Kafka password a secret

- README.md
- lib/fluent/plugin/in_kafka.rb
- lib/fluent/plugin/in_kafka_group.rb
- lib/fluent/plugin/kafka_plugin_util.rb
- lib/fluent/plugin/out_kafka.rb
- lib/fluent/plugin/out_kafka2.rb
- lib/fluent/plugin/out_kafka_buffered.rb
Solves https://github.com/fluent/fluent-plugin-kafka/issues/189
> Add support for ssl_ca_certs_from_system

- lib/fluent/plugin/in_kafka.rb
- lib/fluent/plugin/in_kafka_group.rb
Now input plugin supports also both SCRAM and PLAIN authentication
> Full SSL authentication support for input plugin

- lib/fluent/plugin/out_rdkafka.rb
This uses https://rubygems.org/gems/rdkafka
This version takes more memory but CPU usage is lower.
> Add rdkafka based output plugin

- lib/fluent/plugin/kafka_producer_ext.rb
> Fix DeliveryFailed signature mismatch with newer ruby-kafka. fix #229

- lib/fluent/plugin/kafka_plugin_util.rb
- lib/fluent/plugin/out_kafka2.rb
Follow https://github.com/zendesk/ruby-kafka/pull/633
> Add ssl_client_cert_chain parameter.

- lib/fluent/plugin/out_rdkafka2.rb
> out_rdkafka2: Add v1 API based rdkafka plugin

- lib/fluent/plugin/kafka_plugin_util.rb
> Follow ruby-kafka 0.7.6 changes. fix #247

- lib/fluent/plugin/out_kafka.rb
- lib/fluent/plugin/out_kafka2.rb
- lib/fluent/plugin/out_kafka_buffered.rb
Similar to #244 but for Kerberos Authentication.
Related to issue  #255
> Added setting to not use SSL with SASL/GSSAPI for Kerberos Authentication

- README.md
I commit Issue : https://github.com/fluent/fluent-plugin-kafka/issues/266
> add support for ouput kafka with lz4 compression

- README.md
I also found ruby-kafka support zstd compression on newest release, I test it and it works!
> add support for ouput kafka with zstd compression

- lib/fluent/plugin/out_kafka2.rb
> out_kafka2: Add connect_timeout / socket_timeout parameters

- lib/fluent/plugin/out_rdkafka.rb
- lib/fluent/plugin/out_rdkafka2.rb
> out_rdkafka2: Share producer between flush threads

- lib/fluent/plugin/in_kafka.rb
- lib/fluent/plugin/in_kafka_group.rb
This replaces the `use_record_time` boolean option with a `time_source` enum option to select the desired time source, with `time_source kafka` providing timestamps from Kafka itself. `use_record_time true` is now a deprecated setting equivalent to `time_source record`.
This also fixes `time_source record` in the `in_kafka` plugin (previously, `use_record_time` did nothing with `in_kafka`, it only worked with `in_kafka_group`).
Note that in order to behave correctly, `time_source kafka` requires a version of ruby-kafka with the fix in https://github.com/zendesk/ruby-kafka/pull/766.
> Add option to use Kafka's timestamps as the time source

- README.md
Tests have been already written.
> Remove obsolete TODO in README

- README.md
- lib/fluent/plugin/out_kafka.rb
- lib/fluent/plugin/out_kafka_buffered.rb
> warn for the end of v0.12

- lib/fluent/plugin/out_rdkafka.rb
- lib/fluent/plugin/out_rdkafka2.rb
> out_rdkafka2: Follow rdkafka's log level for rdkafka log

- fluent-plugin-kafka.gemspec
Fix #326 
I tested `in_kafka_group`/`out_kafka2` with basic configration and no problem.
> Relax ruby kafka dependency

- lib/fluent/plugin/out_kafka2.rb
- lib/fluent/plugin/out_rdkafka2.rb
Configuration example:
```
topic ${app}-data
```
> Add topic parameter to support placeholder based topic name. fix #343

- lib/fluent/plugin/in_kafka_group.rb
> Use ssl_verify_hostname parameter in kafka client setup. fix #325

- lib/fluent/plugin/kafka_producer_ext.rb
Solves error "undefined call method" of partitioner.
Working, but I am not a ruby programmer/expert, check needed.
> Fix for partitioner call method

- lib/fluent/plugin/out_kafka2.rb
- lib/fluent/plugin/out_rdkafka2.rb
> output: Add discard_kafka_delivery_failed in new plugins. fix #356

- lib/fluent/plugin/in_kafka_group.rb
> in_kafka_group: Add add_headers parameter. fix #353

- lib/fluent/plugin/out_kafka2.rb
The wrong type was being used when raising this error.
> Fixed a small bug in the way an exception is raised.

- lib/fluent/plugin/in_kafka.rb
- lib/fluent/plugin/in_kafka_group.rb
- lib/fluent/plugin/in_rdkafka_group.rb
Currently, Kafka input plugins do not handle 3rd party parser plugins.
This PR makes to be able to handle 3rd party plugins on Kafka input plugins.
After applying this PR, Kafka input plugins can work with [fluent-plugin-parser-avro](https://github.com/fluent-plugins-nursery/fluent-plugin-parser-avro).
---
I'd confirmed that kafka input plugins can work with 3rd party plugin with the following configurations:
```aconf
<source>
@type kafka
brokers "localhost:9092"
topics "persons-avro"
format "avro"
<confluent_registry>
url "http://localhost:8081"
subject "persons-avro-value"
schema_key "schema"
</confluent_registry>
</source>
<match **>
@type stdout
</match>
```
```aconf
<source>
@type kafka_group
brokers "localhost:9092"
topics "persons-avro"
format "avro"
consumer_group "mygroup" …
```
> Handle parse section and custom format on Kafka input plugins

- .github/workflows/linux.yml
- ci/prepare-kafka-server.sh
- lib/fluent/plugin/in_kafka_group.rb
- test/helper.rb
- test/plugin/test_in_kafka.rb
- test/plugin/test_in_kafka_group.rb
And also I happened to find another issue for Ruby keyword argument interop on `in_kafka_group` plugin.
Sorry for overlooked it. :cry:
> Add inputs testcases

- .github/workflows/stale-actions.yml
It enable to support maintaining issues.
> github: enable stale actions

- lib/fluent/plugin/out_kafka2.rb
- lib/fluent/plugin/out_rdkafka.rb
fix description for `exclude_message_key` option
> fix description for `exclude_message_key` option

- .github/workflows/linux.yml
- Gemfile
- test/plugin/test_out_rdkafka2.rb
> Add tests for rdkafka2

- .github/workflows/linux.yml
> CI: Drop Ruby 2.4 and 2.5, add 3.1

- README.md
- lib/fluent/plugin/out_kafka2.rb
- test/plugin/test_out_kafka2.rb
Addresses https://github.com/fluent/fluent-plugin-kafka/issues/450
> feat(kafka2): Add `record_key` config param

- README.md
> README.md: Add description about `record_key`

- README.md
- lib/fluent/plugin/in_kafka.rb
- lib/fluent/plugin/in_kafka_group.rb
- lib/fluent/plugin/kafka_plugin_util.rb
- lib/fluent/plugin/out_kafka2.rb
- lib/fluent/plugin/out_rdkafka2.rb
Hey team and happy new year!
This PR fixes https://github.com/fluent/fluent-plugin-kafka/issues/459 and also properly marks `ssl_client_cert_key_password` as secret in `out_rdkafka2` as I just happen to stumble upon it.
> adds ssl client cert key password
